### ISSUE TITLE
11章本文の記述ミスについて

### ISSUE THREAD

**Issue by isshi-hasegawa** [JunichiIto/everydayrails-rspec-jp-2022#12]
11章「テスト駆動開発に向けて」の「レッドからグリーンへ」における「RSpecは次に何を…」で始まる段落内で記述ミスと思しき箇所を発見したので報告します。自分の勘違いであればご容赦ください🙏

以下の`complete?`は、正しくは`completed?`ではないでしょうか？

## スクリーンショット

以下はmobi版をKindle for PCで開いたスクショですが、念の為PDF版など他バージョンでも同様の記述ミスを確認しております〜

<img width="1091" alt="長谷川雅士さんの_Kindle_for_Mac_3_-_Everyday_Rails_-_RSpecによるRailsテスト入門" src="https://user-images.githubusercontent.com/53898556/180593874-684e69d7-04b0-469a-a27d-82b5255bfaef.png">

**Comment by JunichiIto** [comment]
ご報告ありがとうございます！たしかに〜。
のちほど修正しますのでしばらくお待ちください 🙏

**Comment by JunichiIto** [comment]
こちら、さきほど修正版を公開しました。Leanpubから最新版をダウンロードしてご確認ください。
ご報告どうもありがとうございました。

<img width="742" alt="everydayrailsrspec-jp-preview_pdf" src="https://user-images.githubusercontent.com/1148320/181872740-da491fe0-6df0-4d61-b9f4-7fd490ed3891.png">
