### ISSUE TITLE
`bin/setup` を実行すると、`db/schema.rb` が更新される

### ISSUE THREAD

**Issue by urimaro** [JunichiIto/everydayrails-rspec-jp-2022#13]
### 概要

`git clone` 後、`main` ブランチで `bin/setup` を実行すると `db/schema.rb` が更新され、以下のような差分が発生しました

https://github.com/urimaro/everydayrails-rspec-jp-2022/commit/a87355f5910e5a251cebe76903fc453093a84b30

このまま進めることはできますが、気になったので報告いたしました
私の環境の問題でしょうか？

### 再現手順

```
git clone https://github.com/JunichiIto/everydayrails-rspec-jp-2022.git
cd everydayrails-rspec-jp-2022
bin/setup
```

### 環境

- Ruby 3.1.0
- Rails 7.0.2.3

**Comment by JunichiIto** [comment]
ご報告ありがとうございます。
のちほど確認しますのでしばらくお待ちください 🙏

**Comment by JunichiIto** [comment]
返信が遅くなってすいません。こちら確認しました。
たしかにdiffが発生しますね。。
過去のコミットログを見たりして原因を探ろうとしましたが、ちょっとよくわかりませんでした😓

手が空いたときにサンプルコードを修正しておこうと思います。（これまたしばらく先になるかもしれませんが。。）
改めてご報告どうもありがとうございました😃

**Comment by urimaro** [comment]
お忙しい中、確認していただき、ありがとうございました

以下が今回の原因ではないかと思いました

- [Dump the database schema containing the current Rails version.](https://github.com/rails/rails/blob/v7.0.2.3/activerecord/CHANGELOG.md#rails-702-february-08-2022:~:text=Dump%20the%20database%20schema%20containing%20the%20current%20Rails%20version.)

以下、推測に基づいた仮説です

---

1. Rails6.0(※)でdatetime型カラムには `precision: 6` のオプションが設定されるようになった
2. Rails7.0(※)でdatetime型カラムの精度のデフォルトが6桁に変わった
3. 「2」により `schema.rb` には `precision: 6` のオプションが設定されなくなった

上記の結果、Rails6から7にアップグレードした環境では、migrationファイルは実行済みなので `schema.rb` は更新されず差分は生まれない
一方、Rails6からRails7にアップグレードしたアプリケーションを新規にmigrationを実行した場合は、`schema.rb` に差分が生まれてしまう

※ 実際にはActive Record

---

前者が伊藤さんの環境に該当して、後者が私の環境に該当するんじゃないのかなと思ったのでした

**Comment by JunichiIto** [comment]
調査ありがとうございます！

> 以下が今回の原因ではないかと思いました

たしかにこれが原因っぽいです。
厳密に言うと、「Rails7.0.2未満から7.0.2以上にアップグレードした環境」ですね。
サンプルアプリをrails newした時点でRails 7ではあったのですが、7.0.2はまだリリースされていませんでした。

https://github.com/JunichiIto/everydayrails-rspec-jp-2022/commit/9239e2926c40276d167060f4b51e269570438899#diff-4fc9c8a432faa5cdd08955b29ba1ee7a49bfcc684c7b1e702dc71f6aee1fc0e0

手元で確認した結果、

- 7.0.1でbin/setupを実行 → schema.rbに変更なし
- 7.0.2でbin/setupを実行 → schema.rbに変更あり

となりました。これで原因はスッキリです！！😄

**Comment by urimaro** [comment]
> これで原因はスッキリです！！😄

スッキリしたとのことでなによりです！😊
このissueはcloseしていただいて構いません
(他力本願な言い方ですが、修正が終わった際にcloseしたいかも？と思ったのでした)

**Comment by JunichiIto** [comment]
> 他力本願な言い方ですが、修正が終わった際にcloseしたいかも？と思ったのでした

そうですね、僕も修正対応が終わったタイミングでcloseしようと思っていました。
というわけでもうしばらくお待ちください🙏

**Comment by JunichiIto** [comment]
こちら、先ほどサンプルアプリをアップデートしておきました！（ついでにgemもひととおり最新化しました）
https://github.com/JunichiIto/everydayrails-rspec-jp-2022/blob/main/db/schema.rb

また何かお気づきの点があればお気軽にご連絡ください。
あらためてこの度はどうもありがとうございました！

**Comment by urimaro** [comment]
こちらこそ、お忙しい中、ありがとうございました
