### ISSUE TITLE
`bundle exec rspec` を実行すると `ActiveRecord::EnvironmentMismatchError` が発生する

### ISSUE THREAD

**Issue by urimaro** [JunichiIto/everydayrails-rspec-jp-2022#14]
### 概要

`bundle exec rspec` を実行すると `ActiveRecord::EnvironmentMismatchError` が発生します
だだし、specは最後まで実行されます

### 再現手順

書籍の以下の説明に従ってセットアップすると再現します

- 1. イントロダクション - サンプルアプリケーションのセットアップ手順

具体的なコマンドは以下のとおりです

```
git clone https://github.com/JunichiIto/everydayrails-rspec-jp-2022.git
cd everydayrails-rspec-jp-2022
rbenv local 3.1.0
bin/setup
bundle exec rspec
```

SSHではなくHTTPSを使っていますが、特別な理由はありません

### 実際の挙動

実行時のログを添付します(※)

- [log.txt](https://github.com/JunichiIto/everydayrails-rspec-jp-2022/files/10206300/log.txt)

※ issueに貼り付けると期待した通りに改行されなかったので…

### 回避方法

メッセージ通り、以下のコマンドを実行すると、エラーが発生しなくなります

```
bin/rails db:environment:set RAILS_ENV=test
```

### 環境

- Ruby 3.1.0
- Rails 7.0.4
- mainブランチ

### その他

以下のissueと同じ現象だと思うのですが、すでに対策はmergeされているようなので、なぜ発生するのかよくわかっていません

- [Test database is created with environment='development' when running rake db:test:prepare #26731](https://github.com/rails/rails/issues/26731)
- [Ignore test env in DatabaseTasks when DATABASE_URL is present #37351](https://github.com/rails/rails/pull/37351)

Railsをアップグレードすると発生する可能性があるのかもしれないですね…
完全に推測です

**Comment by JunichiIto** [comment]
ご報告ありがとうございます！
また手が空いたときに確認しますのでしばらくお待ちください〜 🙏

**Comment by JunichiIto** [comment]
遅くなってすいません。こちら、時間ができたのでようやく調査できました。

結論からいうと、このアプリ特有の問題ではなく、Rails自体の問題っぽいです。
不具合っぽい挙動を見つけたのでissueを報告しておきました。
原因もここに書いてあります。

[rails db:prepare will save "environment=development" for ar\_internal\_metadata in test database · Issue \#46845 · rails/rails](https://github.com/rails/rails/issues/46845)

最終的にはRails側で問題が解決されるのを待つ必要がありますが、それまでエラーが出続けるのも気持ち悪いので、`bin/setup`実行時に`bin/rails db:environment:set RAILS_ENV=test`も一緒に実行されるようにしておきました。

https://github.com/JunichiIto/everydayrails-rspec-jp-2022/commit/e8bfab7fc1df3d8a6bfab29a4bec4abcf8c21c9a

おそらくこれでエラーは出なくなるはずです。

というわけで、このissue自体はこれでクローズさせてもらいます。
あらためてご報告どうもありがとうございました！

**Comment by JunichiIto** [comment]
追伸
この問題、Rails 7.0.3から発生するようになったみたいです（手元で確かめました）。
ちょっと前にRailsのバージョンアップをしたので、そのタイミングでこの問題が発生するようになったっぽいですね。。

https://github.com/JunichiIto/everydayrails-rspec-jp-2022/commit/63617441438cdad4489a1f0c08c9e3d6ca1d6650#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR5

**Comment by urimaro** [comment]
お忙しい中、調査いただき、ありがとうございました
伊藤さんが立てたissueで対策の議論が進んでいるようで何よりですね☺️

もっと深掘りできるようになると、もう少し色々なことに貢献できると思うので、精進します

**Comment by JunichiIto** [comment]
FYI
PRがマージされてissueがcloseされました 🎉 
次のRailsのリリースぐらいで直ると良いですね😄

https://github.com/rails/rails/issues/46845

**Comment by urimaro** [comment]
FYI.
Railsのブログで紹介されてました😊
https://rubyonrails.org/2023/1/8/this-week-in-rails-first-edition-of-2023-3b0f1bac

**Comment by JunichiIto** [comment]
おー、ほんとだ！情報ありがとうございます！
本来なら urimaro さんの名前が出るべきところかもしれませんが😅
