### ISSUE TITLE
"Active Job" と思われる文言が "Action Job" になっている

### ISSUE THREAD

**Issue by urimaro** [JunichiIto/everydayrails-rspec-jp-2022#16]
PDFのP192「10. その他のテスト - メール送信をテストする」の3行目(コードブロックは除く)において、以下のように記載されています

> このメソッドはAction Jobが UserMailer.welcome_email に提供してくれるメソッドです。

`Action Job` の部分は、正しくは `Active job` なのではないかと思いました。

**Comment by JunichiIto** [comment]
ご報告ありがとうございます！たしかに間違ってますね。。
修正したらまたご連絡します！

**Comment by JunichiIto** [comment]
こちら、修正してアップデートしました！改めてご報告ありがとうございました😄
<img width="781" alt="fixed" src="https://user-images.githubusercontent.com/1148320/222681874-85efd460-24a7-400a-aa06-4b9182f2fa65.png">
