### ISSUE TITLE
5章「コントローラースペック - ユーザー入力をテストする」サンプルコードの修正

### ISSUE THREAD

**Issue by fugakkbn** [JunichiIto/everydayrails-rspec-jp-2022#2]
以下のFactoryのサンプルコードは中括弧(`{}`)が必要ではないかと思い、Issueとして登録しました。
報告する場所として適切でなかったり、思い違いがありましたらご指摘いただけますと幸いです🙇🏻‍♂️

```ruby
# spec/factories/projects.rb
FactoryBot.define do
  ...

  trailt :invalid do
-   name nil
+   name { nil }
  end
end
```

参考：
修正前の状態でのエラーメッセージ

```bash
  1) ProjectsController#create as an authenticated user with invalid attributes does not add a project
     Failure/Error: project_params = FactoryBot.attributes_for(:project, :invalid)
     
     KeyError:
       Trait not registered: "name" referenced within "invalid" definition
     # ./spec/controllers/projects_controller_spec.rb:81:in `block (5 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # KeyError:
     #   Trait not registered: "name" referenced within "invalid" definition
     #   ./spec/controllers/projects_controller_spec.rb:81:in `block (5 levels) in <top (required)>'
```

ご確認よろしくお願いいたします🙏

**Comment by JunichiIto** [comment]
報告ありがとうございます！ご指摘の箇所は下記画像の赤線部分1箇所だけ、という認識で合っていますか？

<img width="1268" alt="Screen Shot 2022-01-25 at 10 57 38" src="https://user-images.githubusercontent.com/1148320/150896660-af560109-2714-46bb-909f-546f3c537484.png">

たしかに中括弧が必要そうですね。修正しておきます！

**Comment by fugakkbn** [comment]
ご確認ありがとうございます！

> ご指摘の箇所は下記画像の赤線部分1箇所だけ、という認識で合っていますか？

はい、そのとおりです。
貼っていただいたように、画像でお伝えした方がわかりやすかったですね…失礼しました🙇🏻‍♂️

**Comment by JunichiIto** [comment]
了解しました。修正できたらまた連絡しますね。

**Comment by JunichiIto** [comment]
@FUGA0618 こちら、さきほど修正しました。最新版をダウンロードしてもらえれば修正されているはずです。

<img width="204" alt="Screen Shot 2022-01-28 at 8 19 12" src="https://user-images.githubusercontent.com/1148320/151459464-a6cd3009-aad4-4480-93ef-932a16858531.png">

ご報告どうもありがとうございました😃

**Comment by fugakkbn** [comment]
最新版をダウンロードして修正いただいた点を確認いたしました。
お忙しいなか早々にご対応いただきありがとうございます 🙏 

そして遅ればせながらRails 7へのご対応もありがとうございます。
Rails 7とRSpecの両方を学ぶことができとても勉強になります 😄
