### ISSUE TITLE
11章「テスト駆動開発に向けて - 外から中へ進む」サンプルコードの訂正

### ISSUE THREAD

**Issue by fugakkbn** [JunichiIto/everydayrails-rspec-jp-2022#3]
節の最後に載っている`app/controllers/projects_controller.rb`のサンプルコード内で`update_attributes`を使用していますが、Rails 6.1で削除済みのメソッドのため、正しくは`update`ではないかと思いました。
以下の画像の赤線の部分です。

<img width="1236" alt="スクリーンショット 2022-01-28 15 45 12" src="https://user-images.githubusercontent.com/58870882/151500546-905b5362-d604-4677-a13f-1550dc942017.png">

GitHub上のサンプルコードの方は`update`になっていました。
https://github.com/JunichiIto/everydayrails-rspec-jp-2022/blob/1340db61ba7324fad3c91109112ee97e71421542/app/controllers/projects_controller.rb#L61-L65

ご確認いただけますと幸いです 🙏

**Comment by JunichiIto** [comment]
ご報告どうもありがとうございます！おっしゃるとおり、変更し忘れですね。。
修正が完了したらまたご連絡します！

**Comment by JunichiIto** [comment]
こちら、さきほど修正しました。最新版をダウンロードしてもらえれば修正されているはずです。

<img width="559" alt="Screen Shot 2022-02-07 at 9 24 33" src="https://user-images.githubusercontent.com/1148320/152708188-0e592322-0ee1-4ddd-b9dd-8470141f0015.png">

ご報告どうもありがとうございました😃
