### ISSUE TITLE
7章リクエストスペックでAPIをテスト - GETリクエストをテストするでも記述ミスについて

### ISSUE THREAD

**Issue by haruguchi-yuma** [JunichiIto/everydayrails-rspec-jp-2022#4]
## 概要
たいしたミスではないのですが😅、コードではなく本書の方でタイポを発見したので報告します。
7章「リクエストスペックでAPIをテスト」の「GETリクエストをテストする」で`見てみましょう`が`見てましょう`となっています。（スクリーンショット参考）

## 該当箇所のスクリーンショット
![image](https://user-images.githubusercontent.com/57053236/151502643-133064fc-75e9-48d0-a11a-5c672b3edc32.png)

ご確認ください🙇‍♂️

**Comment by JunichiIto** [comment]
ご報告ありがとうございます！完全な誤字ですね。。
修正したらまたご連絡します 🙏

**Comment by JunichiIto** [comment]
こちら、さきほど修正しました。最新版をダウンロードしてもらえれば修正されているはずです。

<img width="752" alt="Screen Shot 2022-02-07 at 9 24 05" src="https://user-images.githubusercontent.com/1148320/152708208-80afe2bd-bcbf-47d0-bd46-fce412478770.png">

ご報告どうもありがとうございました😃

**Comment by haruguchi-yuma** [comment]
ご連絡ありがとうございます！:bow:
