### ISSUE TITLE
Better Specsの日本語翻訳ページについて

### ISSUE THREAD

**Issue by nanashisan-prog** [JunichiIto/everydayrails-rspec-jp-2022#5]
[Rails のテストに関するさらなる情報源]->[Better Specs]の説明に
[訳注: Better Specs には日本の翻訳ページもあります]とありますが、見当たりませんでした。
現在も存在しますか？（検索不足でしたらすみません・・・）

2014, 2015年頃の記事には以下のURLが登場しますが、現在404です。
https://www.betterspecs.org/jp/

**Comment by JunichiIto** [comment]
情報ありがとうございます。たしかに日本語版がなくなっていますね。
どうやら2020年8月頃に削除されたようです。背景はちょっとわからないですが・・・。

https://github.com/betterspecs/betterspecs/commit/88c9820a68626549068d613b0a400e3432638e7f

後日Everyday Rails側の記述を修正しておきます。

**Comment by JunichiIto** [comment]
日本語版に関する記述を削除しました。最新版をダウンロードしてもらえれば修正されているはずです。

<img width="734" alt="image" src="https://user-images.githubusercontent.com/1148320/156873094-a328db94-f2db-4d71-8fdb-9b1b84f37c62.png">

ご報告どうもありがとうございました。
